dropoff:
- storage_drop_arm_1
- drop_arm_4
- drop_arm_3
- drop_arm_2
- drop_arm_1
- drop_arm_5
pickup:
- storage_pickup_arm_1
- pickup_arm_4
- pickup_arm_3
- pickup_arm_2
- pickup_arm_1
- pickup_arm_5
