robots:
  - name: "robot1"
    x_pose: 0.67
    y_pose: -14.0
    z_pose: 0.01
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    initial_map: "L1"
    charger: "dock_station_1"
    type: "turtlebot3"

  - name: "robot2"
    x_pose: 0.67
    y_pose: -14.5
    z_pose: 0.01
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    initial_map: "L1"
    charger: "dock_station_2"
    type: "turtlebot3"

  - name: "robot3"
    x_pose: 0.67
    y_pose: -15.0
    z_pose: 0.01
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    initial_map: "L1"
    charger: "dock_station_3"
    type: "turtlebot3"

  - name: "robot4"
    x_pose: 0.67
    y_pose: -15.5
    z_pose: 0.01
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    initial_map: "L1"
    charger: "dock_station_1"
    type: "turtlebot3"

  - name: "robot5"
    x_pose: 0.67
    y_pose: -16.0
    z_pose: 0.01
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    initial_map: "L1"
    charger: "dock_station_2"
    type: "turtlebot3"

  - name: "robot6"
    x_pose: 0.67
    y_pose: -16.5
    z_pose: 0.01
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    initial_map: "L1"
    charger: "dock_station_3"
    type: "turtlebot3"

  - name: "ultra_bot1"
    x_pose: 1.67
    y_pose: -16.0
    z_pose: 0.01
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    initial_map: "L1"
    charger: "dock_station_1"
    type: "fast_turtlebot3"

  - name: "ultra_bot2"
    x_pose: 1.67
    y_pose: -16.5
    z_pose: 0.01
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    initial_map: "L1"
    charger: "dock_station_2"
    type: "fast_turtlebot3"