services:
  ros2_app:
    build: .
    container_name: ros2_jazzy_container
    network_mode: "host"
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      # Магия монтирования: текущая папка на ПК друга (где src) 
      # связывается с папкой /ros2_ws внутри контейнера
      - .:/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    # Оставляем контейнер запущенным и подгружаем ROS окружение
    command: sleep infinity
