robots:
- name: robot1
  x_pose: 4.0
  y_pose: -24.0
  z_pose: 0.01
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
  initial_map: L1
  charger: dock_station_1
  type: turtlebot3
  stay_waypoint: stay_zone_1
  stay_type: park

- name: robot2
  x_pose: 4.0
  y_pose: -27.0
  z_pose: 0.01
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
  initial_map: L1
  charger: dock_station_2
  type: turtlebot3
  stay_waypoint: stay_zone_2
  stay_type: park

- name: robot3
  x_pose: 4.0
  y_pose: -29.0
  z_pose: 0.01
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
  initial_map: L1
  charger: dock_station_2
  type: turtlebot3
  stay_waypoint: stay_zone_3
  stay_type: park

- name: fast_robot1
  x_pose: 31.0
  y_pose: -4.0
  z_pose: 0.01
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
  initial_map: L1
  charger: dock_station_3
  type: fast_turtlebot3
  stay_waypoint: stay_zone_4
  stay_type: park

- name: fast_robot2
  x_pose: 35.0
  y_pose: -4.0
  z_pose: 0.01
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
  initial_map: L1
  charger: dock_station_4
  type: fast_turtlebot3
  stay_waypoint: stay_zone_5
  stay_type: park
- name: robot4
  x_pose: 36.2
  y_pose: -5.3
  z_pose: 0.1
  roll: 0.0
  pitch: 0.0
  yaw: 34.0
  initial_map: L1
  charger: dock_station_4
  type: fast_turtlebot3
  stay_waypoint: dock_station_4
  stay_type: charge
